import type {
  AdCampaignRow,
  AlertRow,
  ConsoleOverview,
  ConsoleReadApi,
  MachineListRow,
  RegionView,
  TopProductRow,
} from "@autovend/contracts";

/* FROZEN demo dataset backing the public /dashboard-demo page — ported from
 * prototype/data.jsx and permanently fake (ARCHITECTURE §3). This file is
 * never wired to the real API; the lead-gated marketing demo must not be able
 * to leak real fleet or revenue data. Every metric is labeled SAMPLE in the UI. */

export const DEMO_REGIONS: RegionView[] = [
  {
    id: "atl",
    name: "Atlanta",
    state: "GA",
    status: "active",
    density: 0.95,
    mapX: 720,
    mapY: 380,
  },
  {
    id: "char",
    name: "Charlotte",
    state: "NC",
    status: "active",
    density: 0.78,
    mapX: 765,
    mapY: 345,
  },
  {
    id: "dc",
    name: "DC Metro",
    state: "DC",
    status: "active",
    density: 0.85,
    mapX: 810,
    mapY: 285,
  },
  {
    id: "nyc",
    name: "NYC Metro",
    state: "NY",
    status: "active",
    density: 0.92,
    mapX: 850,
    mapY: 230,
  },
  { id: "bos", name: "Boston", state: "MA", status: "active", density: 0.7, mapX: 880, mapY: 195 },
  {
    id: "mia",
    name: "South FL",
    state: "FL",
    status: "active",
    density: 0.68,
    mapX: 790,
    mapY: 510,
  },
  { id: "dal", name: "DFW", state: "TX", status: "active", density: 0.74, mapX: 540, mapY: 430 },
  { id: "hou", name: "Houston", state: "TX", status: "active", density: 0.6, mapX: 590, mapY: 470 },
  {
    id: "phx",
    name: "Phoenix",
    state: "AZ",
    status: "active",
    density: 0.55,
    mapX: 290,
    mapY: 410,
  },
  {
    id: "lax",
    name: "LA Metro",
    state: "CA",
    status: "active",
    density: 0.82,
    mapX: 195,
    mapY: 380,
  },
  {
    id: "sfo",
    name: "Bay Area",
    state: "CA",
    status: "active",
    density: 0.78,
    mapX: 130,
    mapY: 290,
  },
  {
    id: "sea",
    name: "Seattle",
    state: "WA",
    status: "active",
    density: 0.65,
    mapX: 175,
    mapY: 130,
  },
  { id: "den", name: "Denver", state: "CO", status: "active", density: 0.6, mapX: 425, mapY: 305 },
  {
    id: "chi",
    name: "Chicago",
    state: "IL",
    status: "active",
    density: 0.88,
    mapX: 660,
    mapY: 245,
  },
  {
    id: "msp",
    name: "Twin Cities",
    state: "MN",
    status: "active",
    density: 0.5,
    mapX: 605,
    mapY: 175,
  },
  {
    id: "nash",
    name: "Nashville",
    state: "TN",
    status: "expansion",
    density: 0.3,
    mapX: 670,
    mapY: 340,
  },
  {
    id: "slc",
    name: "Salt Lake",
    state: "UT",
    status: "expansion",
    density: 0.3,
    mapX: 350,
    mapY: 270,
  },
  {
    id: "pdx",
    name: "Portland",
    state: "OR",
    status: "expansion",
    density: 0.3,
    mapX: 165,
    mapY: 175,
  },
  {
    id: "kc",
    name: "Kansas City",
    state: "MO",
    status: "expansion",
    density: 0.3,
    mapX: 580,
    mapY: 305,
  },
  {
    id: "stl",
    name: "St. Louis",
    state: "MO",
    status: "expansion",
    density: 0.3,
    mapX: 625,
    mapY: 305,
  },
  {
    id: "phl",
    name: "Philadelphia",
    state: "PA",
    status: "expansion",
    density: 0.3,
    mapX: 830,
    mapY: 260,
  },
  {
    id: "orl",
    name: "Orlando",
    state: "FL",
    status: "expansion",
    density: 0.3,
    mapX: 765,
    mapY: 480,
  },
];

export const DEMO_MACHINES: MachineListRow[] = [
  {
    serial: "AV-0421",
    venue: "Midtown Office Tower",
    region: "Atlanta",
    healthPct: 98,
    sales30dMinor: 428000,
    stockPct: 92,
    alerts: 0,
    status: "online",
  },
  {
    serial: "AV-0418",
    venue: "Equinox · Buckhead",
    region: "Atlanta",
    healthPct: 96,
    sales30dMinor: 365000,
    stockPct: 71,
    alerts: 1,
    status: "online",
  },
  {
    serial: "AV-0512",
    venue: "Mercy Health Pavilion",
    region: "Charlotte",
    healthPct: 99,
    sales30dMinor: 510200,
    stockPct: 88,
    alerts: 0,
    status: "online",
  },
  {
    serial: "AV-0488",
    venue: "Capital One Concourse",
    region: "DC Metro",
    healthPct: 88,
    sales30dMinor: 472000,
    stockPct: 34,
    alerts: 2,
    status: "low_stock",
  },
  {
    serial: "AV-0392",
    venue: "Hudson Yards Lobby",
    region: "NYC Metro",
    healthPct: 100,
    sales30dMinor: 684000,
    stockPct: 95,
    alerts: 0,
    status: "online",
  },
  {
    serial: "AV-0367",
    venue: "WeWork · Flatiron",
    region: "NYC Metro",
    healthPct: 92,
    sales30dMinor: 321500,
    stockPct: 64,
    alerts: 0,
    status: "online",
  },
  {
    serial: "AV-0289",
    venue: "Galleria Mall · Lvl 2",
    region: "DFW",
    healthPct: 76,
    sales30dMinor: 210500,
    stockPct: 58,
    alerts: 1,
    status: "service",
  },
  {
    serial: "AV-0301",
    venue: "UCLA Ackerman",
    region: "LA Metro",
    healthPct: 97,
    sales30dMinor: 556000,
    stockPct: 82,
    alerts: 0,
    status: "online",
  },
  {
    serial: "AV-0277",
    venue: "Salesforce Tower",
    region: "Bay Area",
    healthPct: 94,
    sales30dMinor: 498000,
    stockPct: 76,
    alerts: 0,
    status: "online",
  },
  {
    serial: "AV-0241",
    venue: "Logan Airport · Term B",
    region: "Boston",
    healthPct: 99,
    sales30dMinor: 723000,
    stockPct: 91,
    alerts: 0,
    status: "online",
  },
  {
    serial: "AV-0199",
    venue: "Mile High Stadium",
    region: "Denver",
    healthPct: 0,
    sales30dMinor: 0,
    stockPct: 0,
    alerts: 3,
    status: "offline",
  },
  {
    serial: "AV-0156",
    venue: "Northwestern Hosp.",
    region: "Chicago",
    healthPct: 95,
    sales30dMinor: 441000,
    stockPct: 81,
    alerts: 0,
    status: "online",
  },
];

/** Last 30 days, daily gross across the sample fleet, minor units. */
export const DEMO_SALES_DAILY_MINOR: number[] = [
  3120, 3340, 2890, 3580, 4120, 4380, 4210, 3890, 3650, 3920, 4080, 4310, 4520, 4280, 4150, 3980,
  4220, 4480, 4720, 4810, 4690, 4540, 4360, 4580, 4920, 5180, 5240, 5120, 5380, 5460,
].map((dollars) => dollars * 100);

export const DEMO_TOP_PRODUCTS: TopProductRow[] = [
  { name: "Liquid Death · Sparkling 16oz", sku: "LD-SPK-16", units: 8420, mixPct: 9.2 },
  { name: "RXBAR Chocolate Sea Salt", sku: "RX-CSS-1.83", units: 6210, mixPct: 6.8 },
  { name: "Celsius · Tropical Vibe", sku: "CL-TRV-12", units: 5980, mixPct: 6.5 },
  { name: "Skinny Pop · Original 4.4oz", sku: "SP-OG-4.4", units: 5210, mixPct: 5.7 },
  { name: "KIND Bar · Dark Chocolate", sku: "KD-DCN-1.4", units: 4890, mixPct: 5.4 },
  { name: "Olipop · Strawberry Vanilla", sku: "OP-SBV-12", units: 4320, mixPct: 4.7 },
];

export const DEMO_CAMPAIGNS: AdCampaignRow[] = [
  {
    id: "C-0204",
    brand: "Liquid Death",
    flightLabel: "Apr 12 — May 09",
    impressions: 412800,
    ctrPct: 2.4,
    qrScans: 9890,
    status: "live",
  },
  {
    id: "C-0198",
    brand: "Celsius Energy",
    flightLabel: "Apr 01 — Apr 30",
    impressions: 388200,
    ctrPct: 1.9,
    qrScans: 7220,
    status: "live",
  },
  {
    id: "C-0192",
    brand: "Whoop 5.0",
    flightLabel: "Mar 25 — Apr 22",
    impressions: 298100,
    ctrPct: 3.1,
    qrScans: 9180,
    status: "ending",
  },
  {
    id: "C-0181",
    brand: "On Running",
    flightLabel: "Mar 04 — Apr 01",
    impressions: 244500,
    ctrPct: 2.0,
    qrScans: 4870,
    status: "complete",
  },
];

export const DEMO_ALERTS: AlertRow[] = [
  {
    level: "critical",
    machineSerial: "AV-0199",
    venue: "Mile High",
    message: "Heartbeat lost · dispatching field tech",
    agoLabel: "12m",
  },
  {
    level: "warn",
    machineSerial: "AV-0488",
    venue: "Capital One",
    message: "Stock < 35% · 4 SKUs flagged",
    agoLabel: "1h",
  },
  {
    level: "warn",
    machineSerial: "AV-0289",
    venue: "Galleria",
    message: "Vend-fail rate +6% · door sensor",
    agoLabel: "3h",
  },
  {
    level: "info",
    machineSerial: "AV-0418",
    venue: "Equinox",
    message: "Restock complete · 12 SKUs loaded",
    agoLabel: "6h",
  },
];

export const DEMO_OVERVIEW: ConsoleOverview = {
  salesDailyMinor: DEMO_SALES_DAILY_MINOR,
  machinesOnline: DEMO_MACHINES.filter((m) => m.status === "online").length,
  machinesTotal: DEMO_MACHINES.length,
  uptimeLabel: "99.9%",
  adImpressionsLabel: "~1.34M",
  lowStock: DEMO_MACHINES.filter((m) => m.stockPct < 70 && m.status !== "offline").slice(0, 4),
  topProducts: DEMO_TOP_PRODUCTS.slice(0, 5),
  alerts: DEMO_ALERTS,
};

/** Synchronous frozen source; always consumed through the fixtures wrapper so
 * the UI's loading/error/empty branches stay honest. */
export const demoConsoleSource: ConsoleReadApi = {
  getOverview: async () => DEMO_OVERVIEW,
  getMachines: async () => DEMO_MACHINES,
  getSalesDailyMinor: async () => DEMO_SALES_DAILY_MINOR,
  getTopProducts: async () => DEMO_TOP_PRODUCTS,
  getCampaigns: async () => DEMO_CAMPAIGNS,
  getRegions: async () => DEMO_REGIONS,
};
